package gui;

import java.awt.Window;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.Vector;

import javax.swing.JOptionPane;

import peer.Server;


/**
 *
 * @author H2O
 */
public class ServerWindow extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form ServerWindow */
    public ServerWindow(Server serverT) {
    	System.out.println("Create Server");
    	this.server = serverT;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SendButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        UserLisT = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextInputPanel = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayText = new javax.swing.JTextPane();
        a.addWindowListener(new WindowListener(){

		@Override
		public void windowActivated(WindowEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void windowClosed(WindowEvent arg0) {
			// Kill the client Server here
			server.interrupt();
		}

		@Override
		public void windowClosing(WindowEvent arg0) {
			// TODO Auto-generated method stub
		
		}

		@Override
		public void windowDeactivated(WindowEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void windowDeiconified(WindowEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void windowIconified(WindowEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void windowOpened(WindowEvent arg0) {
			// TODO Auto-generated method stub
			
		}});
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server Channel");
        setLocationByPlatform(true);

        SendButton.setFont(new java.awt.Font("Times New Roman", 1, 18));
        SendButton.setText("Send");
        SendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SendButtonMouseReleased(evt);
            }
        });
        UserLisT.setListData(users);
        UserLisT.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return users.size(); }
            public Object getElementAt(int i) { return users.get(i); }
        });
        jScrollPane3.setViewportView(UserLisT);

        TextInputPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextInputPanelKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TextInputPanel);

        displayText.setEditable(false);
        jScrollPane1.setViewportView(displayText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void SendButtonMouseReleased(java.awt.event.MouseEvent evt) {                                         
        // Display msg from input panel to output panel
    	String text = TextInputPanel.getText();
    	TextInputPanel.setText("");
		server.sendString(text);
        
    }                                        

    private void TextInputPanelKeyPressed(java.awt.event.KeyEvent evt) {                                          
        // check for hotkey ALT + S
        if(evt.isControlDown() && (evt.getKeyCode() == KeyEvent.VK_ENTER)){
            TextInputPanel.setText(TextInputPanel.getText()+ "\n");
        }
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        	// Display msg from input panel to output panel
        	evt.consume();
        	String text = TextInputPanel.getText();
        	TextInputPanel.setText("");
    		server.sendString(text);
        }
        else{
        	
        }
    }  
    
    public void addText(String text) {
    	displayText.setText(displayText.getText() + text + "\n");
    }
    
    public void updateUserList(Vector<String> users){
    	this.users = users;
    	UserLisT.setListData(users);
    }
    
    public void Dialog(String msg){
    	JOptionPane.showMessageDialog(null, msg);
    }


    // Variables declaration - do not modify                     
    private Vector<String> users = new Vector<String>(1);
    private javax.swing.JButton SendButton;
    private javax.swing.JTextPane displayText;
    private javax.swing.JTextPane TextInputPanel;
    private javax.swing.JList UserLisT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private Window a= new Window(this);
    private Server server;
    //private Vector[] UserList;
    // End of variables declaration                   

}
